[book]
authors = ["Zhaofeng Li"]
language = "en"
multilingual = false
src = "src"
title = "Tetryx"

[output.html]
git-repository-url = "https://github.com/zhaofengli/tetryx"
edit-url-template = "https://github.com/zhaofengli/tetryx/edit/main/book/{path}"
