name: Deploy Book

on:
  push:
    branches:
      - 'main'

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy-unstable:
    name: Deploy

    runs-on: ubuntu-latest
    if: github.repository == 'zhaofengli/tetryx'

    steps:
      - uses: actions/checkout@v4.1.7

      - uses: DeterminateSystems/nix-installer-action@v18
        continue-on-error: true # Self-hosted runners already have Nix installed

      - name: Install Tetryx
        run: ./.github/install-tetryx-ci.sh

      - name: Configure Tetryx
        run: |
          export PATH=$HOME/.nix-profile/bin:$PATH # FIXME
          tetryx login staging https://staging.tetryx.rs/ "$ATTIC_TOKEN"
          tetryx use tetryx-ci
        env:
          ATTIC_TOKEN: ${{ secrets.ATTIC_TOKEN }}

      - name: Build book
        run: nix build .#book -L

      - name: Copy book artifact
        run: |
          cp --recursive --dereference --no-preserve=mode,ownership result public

      - name: Upload book artifact
        uses: actions/upload-pages-artifact@v3.0.1
        with:
          path: public

      - name: Deploy book
        uses: actions/deploy-pages@v4.0.5

      # TODO: Just take a diff of the list of store paths, also abstract all of this out
      - name: Push build artifacts
        run: |
          export PATH=$HOME/.nix-profile/bin:$PATH # FIXME
          if [ -n "$ATTIC_TOKEN" ]; then
            nix build .#book --no-link --print-out-paths -L | \
              xargs tetryx push tetryx-ci
          fi
        env:
          ATTIC_TOKEN: ${{ secrets.ATTIC_TOKEN }}
